/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TithiTodayRouteImport } from './routes/tithi-today'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MuhuratChoghadiyaRouteImport } from './routes/muhurat.choghadiya'
import { Route as FestivalsYearRouteImport } from './routes/festivals.$year'
import { Route as CompareEphemerisRouteImport } from './routes/compare.ephemeris'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as VratsEkadashiIndexRouteImport } from './routes/vrats.ekadashi.index'
import { Route as VratsEkadashiParanaRouteImport } from './routes/vrats.ekadashi.parana'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TithiTodayRoute = TithiTodayRouteImport.update({
  id: '/tithi-today',
  path: '/tithi-today',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MuhuratChoghadiyaRoute = MuhuratChoghadiyaRouteImport.update({
  id: '/muhurat/choghadiya',
  path: '/muhurat/choghadiya',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsYearRoute = FestivalsYearRouteImport.update({
  id: '/festivals/$year',
  path: '/festivals/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareEphemerisRoute = CompareEphemerisRouteImport.update({
  id: '/compare/ephemeris',
  path: '/compare/ephemeris',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const VratsEkadashiIndexRoute = VratsEkadashiIndexRouteImport.update({
  id: '/vrats/ekadashi/',
  path: '/vrats/ekadashi/',
  getParentRoute: () => rootRouteImport,
} as any)
const VratsEkadashiParanaRoute = VratsEkadashiParanaRouteImport.update({
  id: '/vrats/ekadashi/parana',
  path: '/vrats/ekadashi/parana',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tithi-today': typeof TithiTodayRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compare/ephemeris': typeof CompareEphemerisRoute
  '/festivals/$year': typeof FestivalsYearRoute
  '/muhurat/choghadiya': typeof MuhuratChoghadiyaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/vrats/ekadashi/parana': typeof VratsEkadashiParanaRoute
  '/vrats/ekadashi/': typeof VratsEkadashiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tithi-today': typeof TithiTodayRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compare/ephemeris': typeof CompareEphemerisRoute
  '/festivals/$year': typeof FestivalsYearRoute
  '/muhurat/choghadiya': typeof MuhuratChoghadiyaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/vrats/ekadashi/parana': typeof VratsEkadashiParanaRoute
  '/vrats/ekadashi': typeof VratsEkadashiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/feedback': typeof FeedbackRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reminders': typeof RemindersRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tithi-today': typeof TithiTodayRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compare/ephemeris': typeof CompareEphemerisRoute
  '/festivals/$year': typeof FestivalsYearRoute
  '/muhurat/choghadiya': typeof MuhuratChoghadiyaRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/vrats/ekadashi/parana': typeof VratsEkadashiParanaRoute
  '/vrats/ekadashi/': typeof VratsEkadashiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/feedback'
    | '/mcp'
    | '/privacy'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tithi-today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/compare/ephemeris'
    | '/festivals/$year'
    | '/muhurat/choghadiya'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/vrats/ekadashi/parana'
    | '/vrats/ekadashi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/feedback'
    | '/mcp'
    | '/privacy'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tithi-today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/compare/ephemeris'
    | '/festivals/$year'
    | '/muhurat/choghadiya'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/vrats/ekadashi/parana'
    | '/vrats/ekadashi'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/feedback'
    | '/mcp'
    | '/privacy'
    | '/reminders'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/tithi-today'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/compare/ephemeris'
    | '/festivals/$year'
    | '/muhurat/choghadiya'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/vrats/ekadashi/parana'
    | '/vrats/ekadashi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  FeedbackRoute: typeof FeedbackRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  RemindersRoute: typeof RemindersRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TithiTodayRoute: typeof TithiTodayRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CompareEphemerisRoute: typeof CompareEphemerisRoute
  FestivalsYearRoute: typeof FestivalsYearRoute
  MuhuratChoghadiyaRoute: typeof MuhuratChoghadiyaRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  VratsEkadashiParanaRoute: typeof VratsEkadashiParanaRoute
  VratsEkadashiIndexRoute: typeof VratsEkadashiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tithi-today': {
      id: '/tithi-today'
      path: '/tithi-today'
      fullPath: '/tithi-today'
      preLoaderRoute: typeof TithiTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muhurat/choghadiya': {
      id: '/muhurat/choghadiya'
      path: '/muhurat/choghadiya'
      fullPath: '/muhurat/choghadiya'
      preLoaderRoute: typeof MuhuratChoghadiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/$year': {
      id: '/festivals/$year'
      path: '/festivals/$year'
      fullPath: '/festivals/$year'
      preLoaderRoute: typeof FestivalsYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/ephemeris': {
      id: '/compare/ephemeris'
      path: '/compare/ephemeris'
      fullPath: '/compare/ephemeris'
      preLoaderRoute: typeof CompareEphemerisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vrats/ekadashi/': {
      id: '/vrats/ekadashi/'
      path: '/vrats/ekadashi'
      fullPath: '/vrats/ekadashi/'
      preLoaderRoute: typeof VratsEkadashiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vrats/ekadashi/parana': {
      id: '/vrats/ekadashi/parana'
      path: '/vrats/ekadashi/parana'
      fullPath: '/vrats/ekadashi/parana'
      preLoaderRoute: typeof VratsEkadashiParanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  FeedbackRoute: FeedbackRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  RemindersRoute: RemindersRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TithiTodayRoute: TithiTodayRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CompareEphemerisRoute: CompareEphemerisRoute,
  FestivalsYearRoute: FestivalsYearRoute,
  MuhuratChoghadiyaRoute: MuhuratChoghadiyaRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  VratsEkadashiParanaRoute: VratsEkadashiParanaRoute,
  VratsEkadashiIndexRoute: VratsEkadashiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
